[book]
authors = ["ben"]
language = "zh"
multilingual = false
src = "src"
title = "超级短线交易攻略"

[output.html]
no-section-label = true
git-repository-url = "https://github.com/BenalexCheung/mdbook-don-t-fight-the-tape"
git-repository-icon = "fa-github"

# Enables the `mdbook-template` preprocessor
[preprocessor.template]